const words = {
  easy: [
    "cat","dog","lion","tiger","elephant","monkey",
    "apple","banana","pizza","burger","ice cream",
    "sun","moon","rainbow","cloud","fire",
    "car","bus","train","bicycle","airplane",
    "house","chair","table","bed","door",
    "book","pen","bag","clock","phone",
    "tree","flower","grass","leaf",
    "ball","kite","balloon","gift",
    "shoe","hat","shirt",
    "cake","chocolate","bread",
    "fish","bird","cow","pig",
    "star","ring","key","lamp","sock","bell",
    "cup","spoon","fork","boat","bee","goat",
    "sheep","duck","owl","chicken","crab","shark",
    "whale","turtle","snake","worm","spider","milk",
    "cookie","donut","grape","orange","lemon",
    "carrot","potato","tomato","corn","pear","snow",
    "rain","wind","ice","rock","stone","sand",
    "box","rug","fan","tub","sink","brush",
    "flag", "bone", "boot", "bowl", "cap",
    "card", "coat", "cone", "desk", "drum", "egg",
    "gate", "girl", "glove", "hair",
    "hand", "harp", "horn", "hose", "king",
    "lizard", "nest", "nose", "pencil",
    "pin", "pipe", "pot", "queen", "quill",
    "road", "rose", "ship", "soap",
    "straw", "tank",
    "tent", "toad", "vase", "wall", "watch",
    "wheel", "window", "wing", "yard", "zebra", "ant", "baby",
    "bear", "bottle", "boy", "cart", "chain",
    "cheese", "chin", "church", "circle", "comb",
    "cord", "drawer", "dress", "drop", "ear", "engine",
    "eye", "face", "farm", "feather", "finger",
    "fly", "foot", "fowl", "garden", "goose", "hook", "horse",
    "island", "jewel", "kettle", "knee", "knife", "knot",
    "leg", "library", "line", "lip", "lock", "map",
    "match", "mouth", "nail", "neck", "needle",
    "nerve", "net", "nut", "office", "oven",
    "parcel", "picture", "plate", "plow", "pocket", "prison",
    "pump", "rail", "roof",
    "root", "sail", "school", "scissors", "screw", "seed",
    "shelf", "skin", "skirt", "spade", "sponge", "spring", "square", "stamp",
    "station", "stem", "stick", "stocking", "stomach",
    "store", "street", "tail", "thread", "throat",
    "thumb", "ticket", "toe", "tongue", "tooth", "town",
    "tray", "trousers", "umbrella", "whip", "whistle", "wire"
  ],

  medium: [
    "skateboard","traffic light","headphones","keyboard",
    "doctor","teacher","police","chef","artist",
    "hospital","school","beach","airport",
    "bridge","castle","tower","temple",
    "sandwich","noodles","popcorn",
    "guitar","piano","drum",
    "robot","alien","rocket","spaceship",
    "ghost","vampire","zombie",
    "superhero","pirate","ninja","magician",
    "football","cricket","basketball","tennis",
    "trophy","medal","crown",
    "map","compass","globe",
    "mirror","umbrella","ladder",
    "toothbrush","soap","towel",
    "explosion","tornado","volcano",
    "running","swimming","jumping",
    "calculator","binoculars","flashlight","lantern",
    "campfire","fireworks","hot air balloon","submarine",
    "helicopter","motorcycle","ambulance","firetruck",
    "taxi","tractor","screwdriver","hammer","wrench",
    "scissors","needle","thread","button","zipper",
    "pocket","belt","buckle","shoelace","hourglass",
    "watch","calendar","diary","notebook","poster",
    "banner","flag","shield","sword","bow","arrow",
    "helmet","armor","lighthouse","skyscraper","pyramid",
    "astronaut", "bakery", "barber", "barn",
    "bat", "battery", "beetle", "blimp",
    "bookcase", "bucket", "buffalo", "builder",
    "butterfly", "cabin", "cactus", "cage",
    "camel", "camera", "camping", "candle", "canoe", "canyon",
    "carousel", "carpenter", "carriage", "cart",
    "caterpillar", "cave", "ceiling", "cellar", "cemetery",
    "chariot", "cheetah", "cherry", "chessboard", "chimney",
    "chimpanzee", "clarinet", "cliff", "clover", "clown", "cobweb",
    "coconut", "coffee", "collar", "computer", "cook", "cookie",
    "costume", "cottage", "couch", "cowboy", "crab",
    "crayon", "crocodile", "crystal", "cube", "cupboard",
    "curtain", "cylinder", "daffodil", "dandelion", "deer",
    "dentist", "desert", "desk", "dessert", "dinosaur",
    "diver", "dock", "dolphin", "donkey", "dragon", "dragonfly",
    "dresser", "drill", "drummer", "duster",
    "eagle", "earring", "earth", "easel",
    "eggplant", "elbow", "elevator", "elf", "elk",
    "envelope", "escalator",
    "eyeball", "eyebrow", "eyelash", "fairy", "falcon",
    "family", "fang", "farmhouse", "faucet", "feather", "fence",
    "fern", "ferry", "fireplace",
    "firefly", "fishbowl", "flamingo", "flute",
    "folder", "forest", "fossil", "fountain", "fox",
    "frame", "frog", "furniture",
    "garlic", "gasoline", "gazebo", "generator", "giant", "giraffe",
    "glacier", "glasses", "glove", "goblet",
    "goblin", "goggles", "goldfish", "gorilla", "graduate",
    "greenhouse", "grill", "grizzly", "grocery", "gymnast", "hairbrush",
    "haircut", "hallway", "hamburger", "hammock", "hamster", "handcuff",
    "hangar", "harbor", "harmonica", "harvest", "hatchet", "haystack", "headlight",
    "headset", "heart", "hedgehog", "hero", "highway",
    "hippopotamus", "hobo", "hockey", "honeybee", "hoof", "horizon",
    "horseshoe", "hotdog", "hotel", "houseboat", "houseplant",
    "human", "hummingbird", "hurricane", "hyena", "iceberg",
    "iguana", "infant", "insect", "ivy",
    "jacket", "jaguar", "jail", "jar", "javelin",
    "jellyfish", "jewelry", "jigsaw", "jockey", "judge",
    "juggler", "juice", "jungle", "kangaroo", "kayak",
    "kennel", "ketchup", "kettle",
    "keyboard", "kitchen", "kite", "kitten",
    "kiwi", "knight", "koala", "lamb", "lamp", "lantern",
    "laptop", "lasso", "laundry", "lawnmower", "lawyer",
    "leather", "lemonade", "leopard", "letter", "lettuce", "librarian", "library",
    "license", "lifeboat", "lifeguard", "lightning", "limousine"
  ],

  hard: [
    "microscope","telescope","satellite","drone",
    "earthquake","tsunami","avalanche",
    "galaxy","black hole","constellation",
    "time machine","portal","dimension",
    "brain","skeleton","DNA",
    "gravity","magnet","electricity",
    "democracy","election","protest",
    "detective","mystery","investigation",
    "illusion","shadow","reflection",
    "memory","dream","nightmare",
    "experiment","laboratory","invention",
    "virus","vaccine","pandemic",
    "mutation","evolution","cloning",
    "treasure hunt","secret code","puzzle",
    "maze","labyrinth","escape room",
    "cybersecurity","hacker","password",
    "artificial intelligence","robot army",
    "space station","mars mission",
    "future city","flying car","TikTok", "selfie", "influencer", "meme",
    "Netflix", "YouTube", "gaming",
    "homework", "exam", "result",
    "crush", "love letter", "heartbreak",
    "wifi", "password", "charger"
  ]
};

function getRandomWords(round) {
  let list;

  if (round ===1) list = words.easy;
  else if (round <3) list = words.medium;
  else list = words.hard;

  const shuffled = [...list].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, 3)
}

export default { getRandomWords}